### PR TITLE
add typescript typings

### PR DESCRIPTION
**Pull request by mad-gooze**

### CODE REVIEW

**Comment by tamagokun** [comment]
Thank you! :tada:

**Comment by mad-gooze** [comment]
could you publish npm release please?

**Comment by tamagokun** [comment]
doh, my bad. Published in 4.0.1!

**Comment by mad-gooze** [comment]
Seems like `index.d.ts` is excluded from npm package in `package.json` and was not published.

**Comment by tamagokun** [comment]
ah, of course, I need to add that into `"files"` to have npm publish it. Does it need to be in the same directory as index.js? or can it just live in project root?

**Comment by mad-gooze** [comment]
it should stay in package root

**Comment by tamagokun** [comment]
okay! i've added it in 4.0.2, hopefully it works for you.

**Pull request merged**
